"""init

Revision ID: 23cf5e992324
Revises: 8604fa6df6d2
Create Date: 2023-05-14 14:22:20.117503

"""

# revision identifiers, used by Alembic.
revision = '23cf5e992324'
down_revision = '8604fa6df6d2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
