"""init

Revision ID: 8604fa6df6d2
Revises: dd33cb03d01f
Create Date: 2023-05-14 13:36:29.705319

"""

# revision identifiers, used by Alembic.
revision = '8604fa6df6d2'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
